# Generated by Django 3.2 on 2022-10-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='categoria',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
