# Generated by Django 3.2 on 2022-10-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210320_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Death',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
