# Generated by Django 3.2 on 2022-10-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_name_death_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='category',
            field=models.CharField(choices=[('Resto de ciertas enfermedades infecciosas y parasitarias', 'Resto de ciertas enfermedades infecciosas y parasitarias'), ('Otras causas', 'Otras causas')], max_length=255, null=True),
        ),
    ]
